# Project details
sonar.projectKey=Angular
sonar.projectName=Angular
sonar.projectVersion=1.0

# Source code
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/dist/**

# Tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# TypeScript config
sonar.typescript.tsconfigPath=tsconfig.json

# Code Coverage (Istanbul / Karma)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# SonarQube server
sonar.host.url=http://localhost:9000

# Auth token (example – apna real token yaha paste karna)
sonar.token=squ_c7086bc2a8fc1a0560e3fc7939a0f5cc2a24c8a5

# Encoding
sonar.sourceEncoding=UTF-8

